# Site settings
title: Welcome to my home
description: Index of my website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Duan Xu
user_description: MAY THE FORCE BE WITH YOU! 
user_title: Java Software Developer
email: duanxu@outlook.com
#twitter_username: lorem_ipsum
github_username:  doodle777
gplus_username:  doodlematrix

url_github: "https://github.com/doodle777"
url_weibo: "https://weibo.com/2886472974/"
url_bilibili: "https://space.bilibili.com/3039861/#/"
url_blog: "http://blog.duanxu.science/"


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
